app = "zero-bf6wca"

[build]
  buildpack = "nodejs"

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  [[http_service.checks]]
    path = "/"
    interval = "15s"
    timeout = "5s"
    grace_period = "35s"
    method = "get"

[vm]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
